theme: jekyll-theme-primer
exclude: 
  # 0-foundations
  # - algorithms
  # - aws-ec2
  # - aws-iam
  # - aws-services-overview
  # - aws-storage
  # - command-line-and-git
  # - intro-cloud-and-aws
  # - javascript
  # - phyton
  # - general-reference
  # - interview-prep
  # - logistics
  # - README.md
  - SUMMARY.md
include:
  - .gitbook
