theme: jekyll-theme-primer
exclude: 
  - 1-frontend
  - 2-full-stack
  - 3-backend
  - 4-capstone
  - algorithms
  - general-reference
  - interview-prep
  - logistics
  - README.md
  - SUMMARY.md
include:
  - .gitbook